name: Run Ansible Playbook

on:
  push:
    branches:
      - main  # Change this to your default branch if needed

jobs:
  run-ansible:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Ansible
        run: sudo apt update && sudo apt install -y ansible

      - name: Run Ansible Playbook
        run: ansible-playbook ansible-playbook.yml
