name: Install Tools on Self-Hosted Runner

on: 
  push:
    branches:
      - main  # Change to your default branch if different

jobs:
  install-tools:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      
      - name: Run Ansible Playbook
        run: ansible-playbook action-runner/ansible-playbook.yml
        env:
          ANSIBLE_HOST_KEY_CHECKING: false

