name: Test Self-Hosted Runner

on: [push]

jobs:
  check-tools:
    runs-on: self-hosted
    steps:
    - name: Print current working directory
      run: pwd

    - name: List all files in the repository
      run: ls -alR

    - name: Check Docker version
      run: docker --version

    - name: Check Maven version
      run: mvn -version

    - name: Check Google Chrome version
      run: google-chrome --version

    - name: Run Ansible Playbook
      run: ansible-playbook ansible-playbook.yml  # Updated path here
      env:
        ANSIBLE_HOST_KEY_CHECKING: false
